version: '3.1'

services:

  horizon-db:
    image: postgres:13.4-alpine
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./scripts/:/docker-entrypoint-initdb.d/
    ports:
      - 54321:5432
    networks:
      - backend
    environment:
      - POSTGRES_USER=horizon-admin
      - POSTGRES_PASSWORD=root

  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    depends_on:
      - horizon-db
    ports:
      - 28081:8082
    environment:
      ADMINER_DEFAULT_SERVER: horizon-db
    networks:
      - backend

  horizon-api:
    build: ./api
    restart: always
    depends_on:
      - horizon-db
    ports:
      - 28080:8081
    networks:
      - backend
    environment:
      WAIT_HOSTS: horizon-db:5432
      MIKRO_ORM_HOST: horizon-db

  # horizon-site:
  #   build: ./site
  #   restart: always
  #   depends_on:
  #     - horizon-api
  #   ports:
  #     - 28080:8080

networks:
  backend:
    driver: bridge
