name: Test

on: [push]

jobs:
  test-back:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci
        working-directory: api

      - name: Run Jest Tests
        run: npm run test
        working-directory: api
